1. Introduction to NumPy and Array Creation

In [4]:
import numpy as np

In [6]:
#Create a 1D NumPy array with the elements [10, 20, 30, 40, 50].
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [12]:
#Create a 2D array of shape (2, 3) using numpy.zeros. 
b=np.zeros(6).reshape(2,3)
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#Use numpy.linspace to create an array of 5 evenly spaced numbers between 0 and 100
a = np.linspace(0,100,5)
a

array([  0.,  25.,  50.,  75., 100.])

2. Array Indexing and Slicing


In [20]:
#Using the 1D array [5, 10, 15, 20, 25, 30]:
#Extract the first 3 elements.
a = np.array([5, 10, 15, 20, 25, 30])
print(a[3:])


[20 25 30]


In [30]:
#Extract every second element.
print(a[1::2])

[10 20 30]


In [32]:
#Change the 4th element to 50 and print the updated array. 
a[3] = 50
print(a)

[ 5 10 15 50 25 30]


3. Reshaping Arrays

In [39]:
#Create a 1D array with 12 elements ranging from 1 to 12 using numpy.arange.
a = np.arange(1,13)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
#Reshape it into a 2D array of shape (3, 4). 
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4. Broadcasting and Element-wise Operations 


In [61]:
#Create a 1D array with elements [1, 2, 3, 4, 5].
#Perform the following operations:
#Add 10 to each element. (2 Marks)
#Multiply each element by 3. (3 Marks)
#Calculate the square of each element. (5 Marks)

a = np.array([1, 2, 3, 4, 5])
print(np.add(a,10))
print(np.multiply(a,3))
sq_a = a**2
print(sq_a)



[11 12 13 14 15]
[ 3  6  9 12 15]
[ 1  4  9 16 25]


5. Basic Statistics with Arrays

In [76]:
#Create a NumPy array representing daily temperatures for a week: [30, 32, 31, 29, 28, 33, 34].
#Find the mean temperature of the week. (3 Marks)
#Find the minimum and maximum temperatures. (3 Marks)
#Calculate the total sum of the temperatures. (4 Marks)

a = np.array( [30, 32, 31, 29, 28, 33, 34])
print(np.mean(a))
print(np.max(a),np.min(a))
print(np.sum(a))


31.0
34 28
217


6. Real-World Problem: Sales Analysis

In [87]:
a = np.array([ [200, 220, 250, 270, 300],[150, 160, 170, 180, 200]  ])
#Calculate the total sales for each product.
print(np.sum(a,axis =1))
#Calculate the average sales per day. 
print(np.mean(a,axis = 1))
#Find the day with the highest sales for each product
print(np.argmax(a,axis = 1) + 1)

[1240  860]
[248. 172.]
[5 5]
